name: exminses
description: A mini app to track your expenses

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=2.19.0-214.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true