name: exminses
description: A mini app to track your expenses

publish_to: 'none' 

version: 0.5.3+1

environment:
  sdk: '>=2.19.0-214.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  i18n_extension: ^5.0.1
  get_it: ^7.2.0
  freezed_annotation: ^2.1.0
  dartz: ^0.10.1
  device_preview: ^1.1.0
  google_fonts: ^3.0.1
  iconify_flutter: ^0.0.4
  colorful_iconify_flutter: ^0.0.2
  equatable: ^2.0.5

  #Firebase
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0

  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: null
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true